from typing import Optional, List, Union, Any
from pydantic import BaseModel
from datetime import datetime, date
from uuid import UUID

class EntityBase(BaseModel):
    entity_name: str
    entity_code: str
    company_size: Optional[str] = None
    contact: Optional[str] = None
    email: Optional[str] = None
    address_1: Optional[str] = None
    address_2: Optional[str] = None
    city: Optional[str] = None
    state: Optional[str] = None
    country: Optional[str] = None
    time_zone: Optional[str] = None            # "Timezone": optional, else auto-derived from country
    date_format: Optional[str] = None          # optional, else auto-derived from country's locale
    default_language: Optional[str] = None
    default_currency: Optional[str] = None
    fiscal_year_start: Optional[str] = None
    week_starts_on: Optional[str] = None
    use_default_localization: bool = False
    # NOTE: when use_default_localization=true, default_language/time_zone/
    # default_currency/date_format/fiscal_year_start/week_starts_on above are
    # all overridden with the tenant's own values (see create_entity()) —
    # whatever is supplied for them here is then ignored.
    # Branch profile (Add-branch form)
    location_type: Optional[str] = None
    is_headquarters: bool = False
    phone: Optional[str] = None
    tax_registration: Optional[str] = None
    postal_code: Optional[str] = None
    # Operating schedule (defaults)
    working_days: Optional[str] = None
    business_hours_start: Optional[str] = None
    business_hours_end: Optional[str] = None
    observes_dst: bool = False
    # Compliance & documents (file references / URLs)
    business_registration_doc: Optional[str] = None
    tax_certificate_doc: Optional[str] = None
    incorporation_certificate_doc: Optional[str] = None
    data_processing_agreement_doc: Optional[str] = None
    insurance_certificate_doc: Optional[str] = None
    other_documents_doc: Optional[str] = None
    # NOTE: active / deleted are operational/backend-managed — not part of the
    # CRUD schema. active defaults to true and deleted to false on create; the
    # delete endpoint flips them.

# NOTE: time_zone / date_format may be supplied directly; when omitted they
# are autogenerated from country_code. time_zone_offset / time_format /
# date_time_format are always autogenerated server-side (master_countries /
# master_locales) and appear only in responses.

class EntityCreate(EntityBase):
    pass

class EntityUpdate(BaseModel):
    entity_name: Optional[str] = None
    entity_code: Optional[str] = None
    company_size: Optional[str] = None
    contact: Optional[str] = None
    email: Optional[str] = None
    address_1: Optional[str] = None
    address_2: Optional[str] = None
    city: Optional[str] = None
    state: Optional[str] = None
    country: Optional[str] = None
    time_zone: Optional[str] = None
    date_format: Optional[str] = None
    default_language: Optional[str] = None
    default_currency: Optional[str] = None
    fiscal_year_start: Optional[str] = None
    week_starts_on: Optional[str] = None
    use_default_localization: Optional[bool] = None
    location_type: Optional[str] = None
    is_headquarters: Optional[bool] = None
    phone: Optional[str] = None
    tax_registration: Optional[str] = None
    postal_code: Optional[str] = None
    working_days: Optional[str] = None
    business_hours_start: Optional[str] = None
    business_hours_end: Optional[str] = None
    observes_dst: Optional[bool] = None
    business_registration_doc: Optional[str] = None
    tax_certificate_doc: Optional[str] = None
    incorporation_certificate_doc: Optional[str] = None
    data_processing_agreement_doc: Optional[str] = None
    insurance_certificate_doc: Optional[str] = None
    other_documents_doc: Optional[str] = None

class EntityResponse(EntityBase):
    entity_id: UUID
    # Autogenerated server-side (read-only); time_zone/date_format are inherited from the base.
    time_zone_offset: Optional[str] = None
    time_format: Optional[str] = None
    date_time_format: Optional[str] = None
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True

class EntityListResponse(BaseModel):
    entities: List[EntityResponse]
    total: int
    page: int
    size: int
    pages: int
